services:
     
  cm:
    image: custom-sxa-xm1-cm:${SITECORE_VERSION}
    build:
      context: ./build/cm
      args:
        BASE_IMAGE: ${SITECORE_DOCKER_REGISTRY}sitecore-xm1-cm:${SITECORE_VERSION}
        SPE_RESOURCES_IMAGE: ${SITECORE_DOCKER_REGISTRY}modules/sitecore-spe-assets:${SITECORE_SPE_VERSION}
        SXA_RESOURCES_IMAGE: ${SITECORE_DOCKER_REGISTRY}modules/sitecore-sxa-xm1-assets:${SITECORE_VERSION}
  
  cd:
    image: custom-sxa-xm1-cd:${SITECORE_VERSION}
    build:
      context: ./build/cd
      args:
        BASE_IMAGE: ${SITECORE_DOCKER_REGISTRY}sitecore-xm1-cd:${SITECORE_VERSION}
        SXA_RESOURCES_IMAGE: ${SITECORE_DOCKER_REGISTRY}modules/sitecore-sxa-xm1-assets:${SITECORE_VERSION}